import "@/styles/globals.css";

import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TempatNugas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.className} antialiased`}>
        <>{children}</>
      </body>
    </html>
  );
}
