// export const events = ({ event }: { event: IEvent }) => [
//   {
//     id: 1,
//     title: "Bekerja bersama Spoengebob",
//     datetime: "21 Juli 2024 10:00 WIB",
//     workplace: "Krusty Krab",
//     address: "Seberang Chum Bucket",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales nisi non urna pharetra scelerisque. Praesent lobortis ante a arcu fringilla, vel eleifend lectus finibus. Nullam bibendum eu nunc nec malesuada. Pellentesque porta condimentum neque ut tincidunt. Praesent suscipit fermentum vestibulum. Morbi dignissim rhoncus ante ac tempor. Quisque posuere massa arcu, sit amet placerat massa consequat at. In placerat ante nulla, ut viverra turpis tincidunt sit amet. Sed eu mattis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor vulputate efficitur. Donec nec neque metus. Curabitur quis cursus risus, lacinia suscipit risus. Nulla ultrices felis vel velit cursus finibus Curabitur a aliquam libero, rutrum imperdiet erat. Nullam vehicula erat non lacinia varius. Donec tempus consectetur felis, eget porttitor sapien pretium ut. Donec nisi nisi, porttitor ac fermentum nec, tempus in dui. Cras consectetur interdum mi, ut luctus mauris lobortis sit amet. Nulla ultrices ex eget arcu condimentum, non commodo tellus fringilla. Nullam dignissim pretium neque, vitae dignissim dui egestas vitae. Sed at nibh pretium, varius nisi non, ornare nisl. Curabitur velit eros, pellentesque a nunc in, rhoncus vehicula quam. Mauris viverra nibh leo, sit amet ultrices sapien tempus in. Ut eu ornare massa. Suspendisse potenti. Sed efficitur ipsum vel vehicula malesuada. Nullam at quam justo. Nunc eu leo odio. Morbi pretium eros sem, ut congue lectus commodo vitae. Mauris consequat ullamcorper dignissim. Aliquam eu orci maximus, facilisis tellus interdum, condimentum nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque vestibulum risus lacus. Quisque enim diam, aliquet nec bibendum ac, ultricies ac ligula. Duis sapien risus, tempor sed odio sit amet, blandit rhoncus sapien.",
//     user: "Spongebob Squarepants",
//   },
//   {
//     id: 2,
//     title: "WFC with Hokage",
//     datetime: "21 November 2038 10:00 WIB",
//     workplace: "Ichiraku Ramen",
//     address: "Di pinggir jalan",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales nisi non urna pharetra scelerisque. Praesent lobortis ante a arcu fringilla, vel eleifend lectus finibus. Nullam bibendum eu nunc nec malesuada. Pellentesque porta condimentum neque ut tincidunt. Praesent suscipit fermentum vestibulum. Morbi dignissim rhoncus ante ac tempor. Quisque posuere massa arcu, sit amet placerat massa consequat at. In placerat ante nulla, ut viverra turpis tincidunt sit amet. Sed eu mattis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor vulputate efficitur. Donec nec neque metus. Curabitur quis cursus risus, lacinia suscipit risus. Nulla ultrices felis vel velit cursus finibus Curabitur a aliquam libero, rutrum imperdiet erat. Nullam vehicula erat non lacinia varius. Donec tempus consectetur felis, eget porttitor sapien pretium ut. Donec nisi nisi, porttitor ac fermentum nec, tempus in dui. Cras consectetur interdum mi, ut luctus mauris lobortis sit amet. Nulla ultrices ex eget arcu condimentum, non commodo tellus fringilla. Nullam dignissim pretium neque, vitae dignissim dui egestas vitae. Sed at nibh pretium, varius nisi non, ornare nisl. Curabitur velit eros, pellentesque a nunc in, rhoncus vehicula quam. Mauris viverra nibh leo, sit amet ultrices sapien tempus in. Ut eu ornare massa. Suspendisse potenti. Sed efficitur ipsum vel vehicula malesuada. Nullam at quam justo. Nunc eu leo odio. Morbi pretium eros sem, ut congue lectus commodo vitae. Mauris consequat ullamcorper dignissim. Aliquam eu orci maximus, facilisis tellus interdum, condimentum nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque vestibulum risus lacus. Quisque enim diam, aliquet nec bibendum ac, ultricies ac ligula. Duis sapien risus, tempor sed odio sit amet, blandit rhoncus sapien.",
//     user: "Spongebob Squarepants",
//   },
//   {
//     id: 3,
//     title: "Kerja bareng Hoshina Fukutaichou",
//     datetime: "21 November 2045 15:00 WIB",
//     workplace: "Pecel Lele bu Astuti",
//     address: "Jalan Ikan Paus",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales nisi non urna pharetra scelerisque. Praesent lobortis ante a arcu fringilla, vel eleifend lectus finibus. Nullam bibendum eu nunc nec malesuada. Pellentesque porta condimentum neque ut tincidunt. Praesent suscipit fermentum vestibulum. Morbi dignissim rhoncus ante ac tempor. Quisque posuere massa arcu, sit amet placerat massa consequat at. In placerat ante nulla, ut viverra turpis tincidunt sit amet. Sed eu mattis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor vulputate efficitur. Donec nec neque metus. Curabitur quis cursus risus, lacinia suscipit risus. Nulla ultrices felis vel velit cursus finibus Curabitur a aliquam libero, rutrum imperdiet erat. Nullam vehicula erat non lacinia varius. Donec tempus consectetur felis, eget porttitor sapien pretium ut. Donec nisi nisi, porttitor ac fermentum nec, tempus in dui. Cras consectetur interdum mi, ut luctus mauris lobortis sit amet. Nulla ultrices ex eget arcu condimentum, non commodo tellus fringilla. Nullam dignissim pretium neque, vitae dignissim dui egestas vitae. Sed at nibh pretium, varius nisi non, ornare nisl. Curabitur velit eros, pellentesque a nunc in, rhoncus vehicula quam. Mauris viverra nibh leo, sit amet ultrices sapien tempus in. Ut eu ornare massa. Suspendisse potenti. Sed efficitur ipsum vel vehicula malesuada. Nullam at quam justo. Nunc eu leo odio. Morbi pretium eros sem, ut congue lectus commodo vitae. Mauris consequat ullamcorper dignissim. Aliquam eu orci maximus, facilisis tellus interdum, condimentum nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque vestibulum risus lacus. Quisque enim diam, aliquet nec bibendum ac, ultricies ac ligula. Duis sapien risus, tempor sed odio sit amet, blandit rhoncus sapien.",
//     user: "Hoshina Soshiro",
//   },
// ];
